version: '3.8'
services:
  pg-tasks:
    container_name: pg-user
    image: postgres:10
    ports:
      - 5433:5432  # porta externa:porta interna em relação ao container
    environment:
      - POSTGRES_DB=userDB
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres

  user_service:
    container_name: user-service
    image: zemiro/user_service_image
    environment:
      - DATABASE_HOST=localhost
      - DATABASE_USER=postgres
      - DATABASE_PASSWD=password
    ports:
      - "8080:8080"
    network_mode: host