global:
  scrape_interval: 15s

scrape_configs:
#  - job_name: 'prometheus'
#    static_configs:
#      - targets: ['localhost:9090']
#
#  - job_name: 'jaeger'
#    metrics_path: /metrics
#    static_configs:
#      - targets: ['jaeger:14269']

  - job_name: 'user-service-job'
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ['172.17.0.1:8081']
        labels:
          application: "api-user-service"