spring:
  config:
    import: "optional:configserver:http://localhost:8888" # Importa as configurações do Config Server
  cloud:
    config:
      uri: http://localhost:8888 # URL do seu Config Server
      name: user-service-config # Nome do repositório no Config Server
      profile: dev # Perfil ativo
      label: main # Branch do repositório (opcional)
    compatibility-verifier:
      enabled: false