spring:
  application:
    name: user-service
  profiles:
    active: local

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path=/api-docs:

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  server:
    renewal-percent-threshold: 0.85