name: Deploy Application User-Service

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install
      - name: Login No Docker Hub
        run: echo "${{secrets.DOCKER_HUB_PASSWORD}}" | docker login -u "${{secrets.DOCKER_HUB_USER}}" --password-stdin
      - name: Build Docker Image
        run: docker build -t zemiro/user_service_image .
      - name: Push image docker
        run: docker push zemiro/user_service_image